name: Build and Pre-release

on:
  pull_request:
    types: [closed]
    branches:
      - master

permissions: write-all

jobs:
  build:
    if: github.event.pull_request.merged == true
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up repository
        uses: actions/checkout@master

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jdk+fx

      - name: Run Clean Checks
        run: ./gradlew clean check

  release:
    if: github.event.pull_request.merged == true
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up repository
        uses: actions/checkout@master

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jdk+fx

      - name: Build Jar
        run: ./gradlew clean shadowJar

      - name: Create Pre-Release
        id: create_pre_release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: true
          files: build/libs/clinicmate.jar
          name: Development Pre-release
          tag_name: dev
          fail_on_unmatched_files: true
          token: ${{ secrets.GITHUB_TOKEN }}
